/*******************************************************************************
 * Generated by firmware/fonts/generate_pixel_fonts.py
 * Source: fonts/QuinqueFive.otf
 * Size: 10 px
 * Bpp: 1
 * Notes: Pillow fontmode=1, no antialiasing, custom codepoint set, handcrafted 2x2 '.', 3px digit gaps
 ******************************************************************************/

#include "lvgl.h"

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {
    0xf0, 0xff, 0xff, 0xfc, 0x0f, 0x03, 0xc0, 0xf0, 0x3c, 0x0f, 0x03, 0xff,
    0xff, 0xf0, 0x3c, 0x0f, 0x0c, 0xc3, 0x30, 0x0c, 0x03, 0x00, 0xc0, 0x30,
    0xff, 0xff, 0xf0, 0xff, 0x3f, 0xc0, 0x0c, 0x03, 0x0f, 0x03, 0xc3, 0x00,
    0xc0, 0xff, 0xff, 0xf0, 0xff, 0xff, 0xf0, 0x0c, 0x03, 0x3f, 0xcf, 0xf0,
    0x0c, 0x03, 0xff, 0xff, 0xf0, 0xc0, 0xf0, 0x3c, 0x0f, 0x03, 0xff, 0xff,
    0xf0, 0x0c, 0x03, 0x00, 0xc0, 0x30, 0xff, 0xff, 0xfc, 0x03, 0x00, 0xff,
    0xff, 0xf0, 0x0c, 0x03, 0xff, 0xff, 0xf0, 0xff, 0xff, 0xfc, 0x03, 0x00,
    0xff, 0xff, 0xfc, 0x0f, 0x03, 0xff, 0xff, 0xf0, 0xff, 0xff, 0xf0, 0x0c,
    0x03, 0x03, 0x00, 0xc0, 0xc0, 0x30, 0x30, 0x0c, 0x00, 0xff, 0xff, 0xfc,
    0x0f, 0x03, 0xff, 0xff, 0xfc, 0x0f, 0x03, 0xff, 0xff, 0xf0, 0xff, 0xff,
    0xfc, 0x0f, 0x03, 0xff, 0xff, 0xf0, 0x0c, 0x03, 0xff, 0xff, 0xf0
};

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {
    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},
    {.bitmap_index = 0, .adv_w = 96, .box_w = 2, .box_h = 2, .ofs_x = 1, .ofs_y = -2},
    {.bitmap_index = 1, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 14, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 27, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 40, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 53, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 66, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 79, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 92, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 105, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
    {.bitmap_index = 118, .adv_w = 192, .box_w = 10, .box_h = 10, .ofs_x = 0, .ofs_y = -2},
};

static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = 46,
        .range_length = 1,
        .glyph_id_start = 1,
        .unicode_list = NULL,
        .glyph_id_ofs_list = NULL,
        .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY,
    },
    {
        .range_start = 48,
        .range_length = 10,
        .glyph_id_start = 2,
        .unicode_list = NULL,
        .glyph_id_ofs_list = NULL,
        .list_length = 0,
        .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY,
    },
};

static const lv_font_fmt_txt_dsc_t font_dsc = {
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 2,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0,
};

const lv_font_t lv_font_quinquefive_10_digits = {
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = 10,
    .base_line = 2,
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = 0,
    .underline_thickness = 0,
    .static_bitmap = 0,
    .dsc = &font_dsc,
    .fallback = NULL,
    .user_data = NULL,
};
